=== artas360/wolvm/config/VMmanager.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Issam REBAI (EMB) -->
<!ELEMENT WolVM (kernelPath, VMTypes, VMmanagers)>
<!ATTLIST WolVM
	version CDATA #REQUIRED
	datetime CDATA #IMPLIED
>
<!ELEMENT kernelPath (#PCDATA)>
<!ELEMENT VMTypes (VMType+)>
<!ELEMENT VMType (check, list, mac, launchVM)>
<!ATTLIST VMType
	id ID #REQUIRED
	name CDATA #REQUIRED
	version CDATA #REQUIRED
	os CDATA #IMPLIED
>
<!ELEMENT check (#PCDATA)>
<!ELEMENT list (#PCDATA)>
<!ATTLIST list
	regex CDATA #REQUIRED
	numRegexGroup CDATA "1"
>
<!--Regex used to retrieve the list of the VM names-->
<!ELEMENT mac (#PCDATA)>
<!ATTLIST mac
	regex CDATA #REQUIRED
	numRegexGroup CDATA "1"
>
<!--Regex used to retrieve the MAC address-->
<!ELEMENT launchVM (#PCDATA)>
<!ELEMENT VMmanagers (VMmanager*)>
<!ELEMENT VMmanager (#PCDATA)>
<!ATTLIST VMmanager
	name CDATA #REQUIRED
	type IDREF #REQUIRED
	path CDATA #REQUIRED
>

=== artas360/wolvm/config/wolvm_configure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WolVM SYSTEM "VMmanager.dtd">
<WolVM datetime="2012-04-18 16:00" version="0.1">
	<kernelPath>../../noyau/daemon/daemon</kernelPath>
	<VMTypes>
		<VMType id="oracleVM" name="virtualbox" version="4.1.12" >
			<check>vboxmanage</check>
			<list regex="([a-zA-Z0-9_-]+)" numRegexGroup="1">vboxmanage list vms</list>
			<mac regex="MAC: ([0-9A-F]{12})" numRegexGroup="1">vboxmanage showvminfo</mac>
			<launchVM>vboxmanage startvm</launchVM>
		</VMType>

	</VMTypes>
	<VMmanagers>
		<VMmanager type="oracleVM" name="Ma machine de test virtual box" path="C:\Program Files\Oracle\VirtualBox\">text</VMmanager>
	</VMmanagers>
</WolVM>
